### ISSUE TITLE
No style sheet

### ISSUE THREAD

**Issue by xmeah** [HaeckDesign/triangle#1]
Yes, I did purchase the Theme on 03-02-2016, and downloaded it: but there is no style sheet.

**Comment by DavidKarasek** [comment]
Two things.

First, did you check under assets/css ? It appears to be there. Style.less is the file name.

Second, you really shouldn't share a paid for product in a publicly available area like this. @HaeckDesign wouldn't appreciate that and this should be edited/removed for that reason.

**Comment by HaeckDesign** [comment]
Less & CSS files (core,min,custom) are under assets/css
