### ISSUE TITLE
Documentation on Theme Customisation

### ISSUE THREAD

**Issue by jusuchin85** [HaeckDesign/triangle#2]
**From [haeckdesign.com](https://haeckdesign.com/freebies/themes/triangle-ghost-theme)**:

> Navigation, sharing buttons, tabs, icons, alerts, overlays, forms, animations, dropdowns, modals, toggles... it's all in there. Just follow the simple documentation and you're off at a sprinters pace

Might be a dumb question, but where do I find the documentation to enable/disable certain options?

This is an awesome theme, by the way. Lightweight and minimal! 👍

**Comment by HaeckDesign** [comment]
Thank you & apologies for the delay. Have been really bogged down w/ work the last couple months, but I will be releasing an update here soon and I'll be sure to include a little more documentation. I did try to include notes in the comments, but feel free to drop me a message on Twitter (@haeckdesign) if there's anything I can offer a suggestion on.
